A = input('digite algo:')
print('o seu tipo primitivo é',type(A))
print('é alfabético?',A.isalpha())
print('é um digito? ',A.isdigit())
print('é numérico?',A.isnumeric())
print('é decimal?',A.isdecimal())
print('é alfabetico ou/e númerico?',A.isalnum())
print('é com letras minúsculas?',A.islower())
print('é espaço?',A.isspace())
print('é capitalizado?',A.istitle())
print('é com letras maiuscúlas?',A.isupper())
print('é uma identidade?',A.isidentifier())
