nome = str(input('digite o seu nome completo: '))
print('analisando o seu nome...')
print('a quantidade de caracteres que tem em seu nome é {}'.format(len(nome)))
print('O seu nome todo em minúsculo fica {}'.format(nome.lower()))
print('O seu nome todo em maiúsculo fica {}'.format(nome.upper()))
print('A quantidade de letras do seu nome é de {}'.format(len(nome) - nome.count(' ')))
#print('O seu primeiro nome tem {} letras(caracteres)'.format(nome.find(' ')))
nomed = nome.split()
#print('A quantidade de caracteres do seu nome sem considerar os espaços é de {}'.format(len(''.join(nomed))))
print('o seu primeiro nome é {} e ele tem {} letras'.format((nomed[0]), len(nomed[0])))